### ISSUE TITLE
creating hooks as per documentation doesnt work

### ISSUE THREAD

**Issue by Xsmael** [PrestaShop/docs#101]
from this link : https://devdocs.prestashop.com/1.7/themes/reference/hooks/

I followed all the instructions but I can't find my new hook among the positions in the back office, until i entered the Database to manually add an entry in `ps_hooks` table. is this the right way to do ? 

or what  happened ?

am surprised we cannot do that from the UI of the back office and had to play with the DB.

**Comment by PierreRambaud** [comment]
Hi,

You must have a look on https://devdocs.prestashop.com/1.7/modules/concepts/hooks/ 
Hooks are register with `install` method. If you add new hooks after installed your module, you need to reset it :)

Regards

**Comment by Xsmael** [comment]
In the manual they showed two way to create hooks: 
##From a regular PHP file:

Hook::exec('MyCustomHook');
 or 
##From a Smarty template:

{hook h='MyCustomHook'}

I choose the later for simplicity but it didnt work

**Comment by PierreRambaud** [comment]
It's not to create Hook, it call a registered hook.
The wording is not clear, but your are looking for Theme hook.

The procedure is : 
* Create a module
* Add some hook with `registerHook` during `install()` process. [(Register Hook)](https://devdocs.prestashop.com/1.7/modules/concepts/hooks/#registration)
  * if something wrong, uninstall and install module again
* Add methods corresponding to the selected hook. [(Execute hook)](https://devdocs.prestashop.com/1.7/modules/concepts/hooks/#execution)

If you create a custom theme and want to add a custom hook for example `MyAwesomeDesign`:
```smarty
<div>
  {hook h='MyAwesomeDesign'}
</div>
```

You must have this in your module:
```php
    public function install()
    {
        return parent::install() && $this->registerHook('MyAwesomeDesign');
    }

   public function hookMyAwesomeDesign()
   {
        // Something I want to do while calling 'MyAwesomeDesign' hook in my theme
   }
```

Hope I help you =)

**Comment by Xsmael** [comment]
Thank you for your patience with me.

Acutally,  I dont want to create a new module, but to set a hook in the theme, that i can see in the back office and place an existing module there.

**Comment by PierreRambaud** [comment]
No probleme, I'm here to help you :)

The only way to register a hook in database is to have a module which use the `registerHook` function.
Without module, a hook is useless, in my previous example, hook is called with `hookMyAwesomeDesign`. So if you create a hook without module, it will never called.

Regards

**Comment by Xsmael** [comment]
how about creating a new hook, for an existing module ?

**Comment by PierreRambaud** [comment]
What do you mean? Adding a new hook in the core? 

Otherwise all registered hooks are related to modules, you can add upgrade directories like this modules: https://github.com/PrestaShop/ps_customtext/tree/master/upgrade to register new hooks or write anything you want during upgrade :)

**Comment by PierreRambaud** [comment]
Hey, just found this link https://devdocs.prestashop.com/1.7/modules/creation/enabling-auto-update/#adding-updating-modules-or-hooks-between-versions

**Comment by mickaelandrieu** [comment]
Hello @Xsmael,

as your questions have been answered I'm closing this.

Feel free to re-open or to open a new issue if you need helps.

**Comment by grzegorzgit** [comment]
So you cannot create hook just in the template, so  you could later position modules to it? Let's say I need two new hooks in product page, but without any specific module, just to have it in "positions" to attach there any module I want. Isn't the theme.yml file for it? If not, then what is the purpose of registering hook in the theme.yml?

**Comment by kpodemski** [comment]
@grzegorzgit you can indeed register new hooks and modules to it, but if module doesn't implement hook properly there's nothing to display

most of modules are treated as [widgets](https://devdocs.prestashop.com/1.7/modules/concepts/widgets/) maybe this helps you out a bit?

**Comment by Stolaweb** [comment]
I have the same problem. I want to register new hook and place in it module (already installed in my shop)

How to do that. I made custom hook in the theme.yml but I cant see it in Positions in the dashboard. How to make it visible to installed modules to move them to it?
