### ISSUE TITLE
Route to products : -{id}{-:id_product_attribute} position changed to end issues

### ISSUE THREAD

**Issue by Brothely** [PrestaShop/docs#1023]
Hi, 

In the Shop Parameters=>SEO & URLS page , when we change the route to products : 
Example : default is {category:/}-{id}{-:id_product_attribute}{rewrite}{-:ean13}.html  changed to => {category:/}{rewrite}{-:ean13}-{id}{-:id_product_attribute}.html  (  **changed -{id}{-:id_product_attribute} to after {-:ean13}**) .

- After makes this changes all works normal in the front page of website , but when we add for one new product combination for product , on the front page of website when click to go product page will be redirect to https://domain.com/pt/index.php?controller=404#/2-tamanho-m ( not found product ).
- But if we remove product combinations for this product , will be works normal again. 

Prestashop 1.7.6.5

Someone can help me ? Please...

![Schema of URLS changed Route to products](https://user-images.githubusercontent.com/63552105/119746380-48bb5b80-be88-11eb-910c-a00acdb352e8.png)

![Example new product combination](https://user-images.githubusercontent.com/63552105/119746411-5a9cfe80-be88-11eb-9679-f4084fcf037c.png)

**Comment by matks** [comment]
Hi @Brothely is this a bug report? I'm confused why you open this issue on https://github.com/PrestaShop/docs/issues/1023 😅

**Comment by Brothely** [comment]
Hi， @matks  

I am a novice and  first time writing on the github.com ， sorry to have caused confusion to you . 
It is possibel can you help me and tell me where I need open my issue to someone help me ? 
thanks !!

**Comment by matks** [comment]
@Brothely everything is explained there 😉  https://devdocs.prestashop.com/1.7/faq/i-need-help/
