### ISSUE TITLE
Document Template hierarchy feature

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/docs#1024]
We need to document template hierarchy feature, for example you can create completely custom product page, only for selected product ID by having:

`theme/your-theme/catalog/product-X.tpl`

where X is ID of your product.

**Comment by matks** [comment]
> We need to document template hierarchy feature, for example you can create completely custom product page, only for selected product ID

If the template being targeted is related to the identifier of the product, then it's a feature that is only usable for merchant? Module and theme developers cannot control database identifiers.

So it should not go into "Module dev guide" or "Theme developer guide" ?

**Comment by kpodemski** [comment]
@matks I'd say it's for theme developers, working with merchants as an agency or something with existing stores :)

**Comment by kpodemski** [comment]
https://devdocs.prestashop-project.org/8/themes/reference/templates/templates-layouts/
