### ISSUE TITLE
[Need Help] How to submit PR for ps_accounts and ps_eventbus?

### ISSUE THREAD

**Issue by arouiadib** [PrestaShop/docs#1061]
In develop, I try to access "Add new Product" from catalog page, but it seems that there is an issue in ps_accounts and ps_eventbus.

> The "PrestaShop\Module\PsEventbus\Repository\IncrementalSyncRepository" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

![Screenshot from 2021-06-30 15-24-44](https://user-images.githubusercontent.com/23559010/123989526-8136e380-d9b8-11eb-968c-1b1b21d089b1.png)

Also When clicking "Add new Product" in  "product edit page"
![Screenshot from 2021-06-30 15-24-58](https://user-images.githubusercontent.com/23559010/123989534-83993d80-d9b8-11eb-97c3-3f1014294530.png)

The problem is resolved  (maybe just a workaround)  by making services of these modules public:
```
services:
  _defaults:
    public: true

```

But how to submit a PR to receive feedback?

**Comment by matks** [comment]
Hi @arouiadib unfortunately these repositories are managed by https://github.com/prestashopcorp/ not https://github.com/prestashop

I forwarded your question to the team of https://github.com/prestashopcorp/ so they are aware some people are willing to contribute to these codebases. But right now these are not available for contribution AFAIK

**Comment by arouiadib** [comment]
Thanks @matks
