### ISSUE TITLE
Warning: require_once(C:/wamp64/www/config/defines.inc.php): failed to open stream: No such file or directory in C:\wamp64\www\prestashop\config\config.inc.php on line 35  Fatal error: require_once(): Failed opening required 'C:/wamp64/www/config/defines.inc.php' (include_path='.;C:\php\pear') in C:\wamp64\www\prestashop\config\config.inc.php on line 35

### ISSUE THREAD

**Issue by Ouz04** [PrestaShop/docs#1072]
J'ai téléchargé le projet sur gitlab pour l'installer en local mais il m'affiche ces erreurs ci-dessus. Pourriez-vous m'aider ?

**Comment by PierreRambaud** [comment]
Hi @Ouz04 
We are sorry, but this repository is about the PrestaShop documentation.
If you need help we recommend you to contact an agency, the PrestaShop support team, or ask on the official slack channel.

Kind regards
