### ISSUE TITLE
Can not access store front office after changing URL.

### ISSUE THREAD

**Issue by Jagdish-J-P** [PrestaShop/docs#1124]
Hello Sir

I have installed prestashop on subdirectory like www.domain.com/sub-dir1/prestashop. It was working after setting up all details, I have changed Shop URL to www.domain.com. 

Now after changing shop URL my front office has stopped working. 

My shop URL is http://amrapalisdesigner.studio

I am getting below error.

This site can’t be reached

The connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_RESET

**Comment by matks** [comment]
Hello, it seems you need help.

I suggest reading the page https://devdocs.prestashop.com/1.7/faq/i-need-help/ but I don't think this is a topic eligible for documentation. I close this issue.
