### ISSUE TITLE
API - Order cart rules can´t be found in Webservice

### ISSUE THREAD

**Issue by DiogoLoureir** [PrestaShop/docs#1133]
I was reading the Prestashop API Documentation and a resource "order cart rules" that i need cannot be found  on the webservice.
Link to Documentation: [https://devdocs.prestashop.com/1.7/webservice/resources/order_cart_rules/](https://devdocs.prestashop.com/1.7/webservice/resources/order_cart_rules/)
![image](https://user-images.githubusercontent.com/73858673/131828454-cb69b436-eed1-4a4f-a142-c099566a2640.png)

**Comment by matks** [comment]
Oups 😅  the documentation is a little ahead of its time

The Order Cart rules have been enabled for WS, but in version 1.7.8.0 that will be released soon, see https://github.com/PrestaShop/PrestaShop/pull/16710

**Comment by matks** [comment]
I answered the question so I close the issue.
