### ISSUE TITLE
Document the partial update feature in ObjectModel

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/docs#1141]
`ObjectModel` has a partial update feature that is hardly used

I was extensively used for the Product page migration, but it's the first real use case in the core (besides `QuickAccess` limited use). It should be more detailed and explained inside the docs

### Note

There were some major bugs in the initial implementation that were fixed in the underdevelopment 8.0 version, we should either backport those fixes in 1.7, or only document the feature for 8.0 as it won't be correctly usable in 1.7 versions as of now

See PR https://github.com/PrestaShop/PrestaShop/pull/25464 for more details about the fixed bugs

**Comment by matks** [comment]
Added to https://github.com/PrestaShop/docs/issues/1325

**Comment by thomasnares** [comment]
Doc added here https://github.com/PrestaShop/docs/pull/1531

**Comment by thomasnares** [comment]
https://devdocs.prestashop-project.org/8/development/components/database/objectmodel/#partial-update-of-an-object

Is it enough ? 
@kpodemski should we close?
