### ISSUE TITLE
Issues with the VueJS documentation

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/docs#1204]
Following the VueJS doc, it's seems that there is somes errors/changes to handle.

- The CLI command to install vuejs will now install a newer version, not the v2.
- vue create is a Vue CLI 3 only command and you are using Vue CLI 2.9.6.
- vue create, in v3/v4, does not allow the _ inside the name of the project.

URL: https://devdocs.prestashop.com/1.7/modules/concepts/templating/vuejs/

**Comment by matks** [comment]
Hello @PrestaEdit can you link the devdocs page to update?

**Comment by PrestaEdit** [comment]
Hi. It's done.

**Comment by matks** [comment]
Thank you.

@NeOMakinG what do you think we should do about https://devdocs.prestashop.com/1.7/modules/concepts/templating/vuejs/ ?

IMO this page contains some content not related to PrestaShop.

**Comment by NeOMakinG** [comment]
We should probably refacto this page

**Comment by matks** [comment]
Added to https://github.com/PrestaShop/docs/issues/1320
