### ISSUE TITLE
Extend symfony service override/decoration

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/docs#1233]
Hi, I struggled for a good time with ClassNotFoundException when trying to override symfony service for the first time.

I was just requiring the one single `src/service.php` file in `mymodule.php`. The catch was that even for one file, you must be using composer.

**Comment by matks** [comment]
@Hlavtox Sorry I find this issue only now. Indeed your code needs to be autoloaded, and the autoload needs to be done before Symfony performs the replacement.

Maybe this is something we could insert in troubleshooting section? https://devdocs.prestashop.com/1.7/faq/
