### ISSUE TITLE
404 link on  docs/modules/testing/resources.md 

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/docs#1261]
Hi,

On this page https://devdocs.prestashop.com/1.7/modules/testing/resources/ (docs/modules/testing/resources.md) on "Core Functional tests" there is a 404 link on "tests/puppeteer folder".

Thank you.

**Comment by Progi1984** [comment]
We should change to `https://github.com/PrestaShop/PrestaShop/tree/1.7.7.x/tests/UI`

@clotairer Do you think you can create a PR ?

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/docs/pull/1290
