### ISSUE TITLE
Figuring out back-office tabs

### ISSUE THREAD

**Issue by scheMeZa** [PrestaShop/docs#129]
It would be nice to have it documented, which I'll do as a common courtesy :)

The goal:
![image](https://user-images.githubusercontent.com/7773361/44922112-bb816180-ad44-11e8-9373-00c38f0f34c7.png)

In my `MYMODULE_NAME.php`, I'm setting up the public `tabs` property:
```php
public $tabs = [
        [
            'name'              => 'Referify',
            'class_name'        => 'AdminWithdrawRequests',
            'visible'           => true,
            'parent_class_name' => 'SELL',
        ],
        [
            'name'              => 'Withdraw Requests',
            'class_name'        => 'AdminWithdrawRequests',
            'visible'           => true,
            'parent_class_name' => 'AdminWithdrawRequests',
        ],
    ];
```

I'll update the documentation to show a better example once I figure this out. I tried omitting "parent_class_name" from the Referify tab's options to see if it would do what I want.

**Comment by kpodemski** [comment]
https://devdocs.prestashop-project.org/8/modules/concepts/controllers/admin-controllers/tabs/#tabs-registration
