### ISSUE TITLE
Adding New Product Problem

### ISSUE THREAD

**Issue by enginteknoloji** [PrestaShop/docs#1314]
Adding New Product Problem
Symfony\Component\Debug\Exception\ FatalThrowableError
in [modules/ets_superspeed/ets_superspeed.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=modules/ets_superspeed/ets_superspeed.php&line=903#line903) (line 903)

            $this->_class_ss_cache->deleteCache('bestsales');
        }
        public function hookActionObjectProductAddAfter($params)
        {
            $this->_class_ss_cache->deleteCache('newproducts');
            if (self::isInstalled($this->name)) {
                $this->hookActionObjectProductUpdateAfter($params);
            }
        }
Ets_superspeed->hookActionObjectProductAddAfter(array('object' => object(Product), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 3)) in [modules/pagecache/pagecache.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=modules/pagecache/pagecache.php&line=2160#line2160) (line 2160)
PageCache::execHook('m', object(Ets_superspeed), 'hookActionObjectProductAddAfter', array('object' => object(Product), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 3)) in [override/classes/Hook.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=override/classes/Hook.php&line=37#line37) (line 37)
Hook::coreCallHook(object(Ets_superspeed), 'hookActionObjectProductAddAfter', array('object' => object(Product), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 3)) in [classes/Hook.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=classes/Hook.php&line=431#line431) (line 431)
HookCore::callHookOn(object(Ets_superspeed), 'actionObjectProductAddAfter', array('object' => object(Product), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 3)) in [classes/Hook.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=classes/Hook.php&line=944#line944) (line 944)
HookCore::exec('actionObjectProductAddAfter', array('object' => object(Product), 'cookie' => object(Cookie), 'cart' => null, 'altern' => 3), null, false, true, false, null, false) in [modules/ets_superspeed/classes/ext/ets_hook](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=modules/ets_superspeed/classes/ext/ets_hook&line=234#line234) (line 234)
Ets_Hook::exec17('actionObjectProductAddAfter', array('object' => object(Product)), null, false, true, false, null, false, array(array('file' => '/home/tkyawclg/domains/elektronikpazartr.com/public_html/classes/ObjectModel.php', 'line' => 628, 'function' => 'exec', 'class' => 'Hook', 'type' => '::'))) in [override/classes/Hook.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=override/classes/Hook.php&line=17#line17) (line 17)
Hook::exec('actionObjectProductAddAfter', array('object' => object(Product))) in [classes/ObjectModel.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=classes/ObjectModel.php&line=628#line628) (line 628)
ObjectModelCore->add(true, false) in [classes/Product.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=classes/Product.php&line=779#line779) (line 779)
ProductCore->add(true, false) in [classes/ObjectModel.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=classes/ObjectModel.php&line=535#line535) (line 535)
ObjectModelCore->save() in [src/PrestaShopBundle/Controller/Admin/ProductController.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=src/PrestaShopBundle/Controller/Admin/ProductController.php&line=431#line431) (line 431)
ProductController->newAction() in [vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php&line=151#line151) (line 151)
HttpKernel->handleRaw(object(Request), 1) in [vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php&line=68#line68) (line 68)
HttpKernel->handle(object(Request), 1, false) in [vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php&line=200#line200) (line 200)
Kernel->handle(object(Request), 1, false) in [ruya/index.php](https://elektronikpazartr.com/ruya/index.php/_profiler/open?_token=Qmj_ok04hzJDfeqRAJdK-9S7MopNc3ELvqenXFFDIpM?file=ruya/index.php&line=82#line82) (line 82)

**Comment by matks** [comment]
Hello @enginteknoloji it looks like you're looking for help.

You can follow https://devdocs.prestashop.com/1.7/faq/i-need-help/ to find where to get help. This repository is not a support channel so I close this issue.
