### ISSUE TITLE
Use the new translator to translate Javascript-save strings

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/docs#1342]
In the old translation system, the smarty function `l` took an optional parameter `js=1` to output a string that could be used in Javascript. 
https://devdocs.prestashop.com/1.7/development/internationalization/translation/using-the-translator/#smarty-templates does not mention how to handle this case with the new translation system.

**Comment by matks** [comment]
Thank you for https://github.com/PrestaShop/docs/pull/1344 . Do we close the issue now?

**Comment by lmeyer1** [comment]
@matks Yes, of course
