### ISSUE TITLE
Internal server error 500 when creating a new category

### ISSUE THREAD

**Issue by Radziasss** [PrestaShop/docs#1359]
I'm trying to create a new category through Presta API. Acually it works (a new category is created) but I receive an error 500 from the server. No additional information, only error 500. I would rather receive an ID of created category at least. Below is my XML. Parent category 362 does exist. Am I missing something?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<category>
	<id/>
	<id_parent>362</id_parent>
	<link_rewrite>
		<language id="1">test-category</language>
	</link_rewrite>
	<name>
		<language id="1">Test category</language>
	</name>
	<active>1</active>
</category>
</prestashop>
```

**Comment by matks** [comment]
Hi @Radziasss I don't think the documentation can help you understand this bug :/ 

I think you should look for help https://www.prestashop-project.org/support/

I close this issue as this is not a to-do item for the documentation
