### ISSUE TITLE
Refactor v8 documentation

### ISSUE THREAD

**Issue by MeKeyCool** [PrestaShop/docs#1365]
For current v8 documentation, I would suggest **Basics** section refactoring : 
* **Installation** => rename to **Requirements**
    * **Development environment** => Move to **Deployment** section
    * **Configuration** => move to **Basics** section + add Environment variables documentation (cf. https://doc.prestashop.com/display/PS17/Installing+PrestaShop+using+the+command-line+script for details)
      > cf. https://github.com/PrestaShop/PrestaShop/issues/23242 for environment variable list.

* **Deployment**
  * => Add [CLI Install](https://doc.prestashop.com/display/PS17/Installing+PrestaShop+using+the+command-line+script) documentation

      > :warning: To discuss with @Julievrz  and/or @eternoendless if we should remove user doc for this devdoc new section.

* **Staying up to date** => rename to **Maintenance** do be consistent with **Deployment** / **Configuration** / **Requirements** / ... sections

> :warning: Think about SEO and url redirection after refactoring.
> :question: Do we use [aliases](https://gohugo.io/content-management/urls/#example-aliases) for redirect ?

**Comment by Julievrz** [comment]
I'm not against moving this section to the devdocs. It seems to target tech users indeed. 
Regarding the renaming of the page, I think we should ask the SEO team for advice. Maybe "Installation" is better than "Requirements" in this sense.

**Comment by MeKeyCool** [comment]
Thanks for your answer @Julievrz ^^
About SEO, I'll search inside Prestashop SA documentation (Have they access to github ? :thinking: )

In fact, the content of actual "Installation" section is ambiguous. It contains more "requirements" than anything else. Furthermore, having both "Installation" and "Deployment" sections is ambiguous.

For dev/contributor purpose, I think we could enhance UX/UI as well. Maybe a "Get started" first page would be cool :thinking: (sounds another subject)

**Comment by MeKeyCool** [comment]
I'll write some detailed description of usage in https://github.com/PrestaShop/PrestaShop/pull/27990
We could reuse this description for future documentation.
