### ISSUE TITLE
Missing results in Algolia search 

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/docs#1391]
search in devdoc algolia for actionFrontControllerSetVariables or offsetGet : no result
search in google : results

**Comment by matks** [comment]
I confirm we have work to do for improving algolia https://github.com/PrestaShop/docs/issues/1052

but so far we were not able to capture and lock time to do it (main focus of last months was PS 8 feature freeze https://build.prestashop.com/news/prestashop-feature-freeze-v8/)

**Comment by jf-viguier** [comment]
ok @matks, can you revert to the old search engine ?

**Comment by matks** [comment]
I really don't want to 😅 the previous search engine was really bad compared to Algolia

**Comment by kpodemski** [comment]
The search feature now works with hooks thanks to @thomasnares
