### ISSUE TITLE
Document missing hooks for v8

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/docs#1447]
List to confirm/document:

`actionFilterDeliveryOptionList` allows to modify the delivery option list result (#[27222](https://github.com/PrestaShop/PrestaShop/issues/27222)).
`actionValidateOrderAfter` allows to be notified after the complete creation of an order (#[23787](https://github.com/PrestaShop/PrestaShop/issues/23787)).
`displayCheckoutBeforeConfirmation` allows to display custom content at the end of checkout process.
`actionOrderStatusUpdate` and `actionOrderStatusPostUpdate` allows to be notified before and after an order status is changed.
`actionPresentPaymentOptions` is called before payment options are presented in front office (#[26259]([https://github.com/PrestaShop/PrestaShop/issues/26259](https://github.com/PrestaShop/PrestaShop/issues/22321)))
`actionGetAdminToolbarButtons` allows you to define buttons and add them to any toolbar in the back office (#[27485]([https://github.com/PrestaShop/PrestaShop/issues/27485](https://github.com/PrestaShop/PrestaShop/issues/22321)))
`actionGetAlternativeSearchPanels` allows to add an additional search panel for external providers in PrestaShop back office
(#[28635]([https://github.com/PrestaShop/PrestaShop/issues/28635](https://github.com/PrestaShop/PrestaShop/issues/22321)))
`dashboardZoneThree` is displayed in the third column of the dashboard (#[25030]([https://github.com/PrestaShop/PrestaShop/issues/25030](https://github.com/PrestaShop/PrestaShop/issues/22321)))
`actionBeforeCreateCartSummaryFormHandler` and `actionAfterCreateCartSummaryFormHandler` - allows to modify form data for the order created from back office (#[22321](https://github.com/PrestaShop/PrestaShop/issues/22321))
`displayBackOfficeEmployeeMenu` allows to modify back office employee menu (#[25008](https://github.com/PrestaShop/PrestaShop/issues/25008))
`displayEmptyModuleCategoryExtraMessage` allows to display an extra message for an empty modules category in back office
(#[28317]([https://github.com/PrestaShop/PrestaShop/issues/28317](https://github.com/PrestaShop/PrestaShop/issues/25008)))
`actionProductFormBuilderModifier` allows to modify the form content on the experimental product page (#[24213](https://github.com/PrestaShop/PrestaShop/pull/24213))
`actionBeforeCreateProductFormHandler`,
`actionAfterCreateProductFormHandler `,
`actionBeforeUpdateProductFormHandler`, and
`actionAfterUpdateProductFormHandler`
allows to modify experimental product page form data
 (#[24213](https://github.com/PrestaShop/PrestaShop/pull/24213))
Product page hooks are included below: 
For the product list:
		actionProductGridDefinitionModifier
		actionProductGridQueryBuilderModifier
		actionProductGridDataModifier
		actionProductGridFilterFormModifier
		actionProductGridPresenterModifier
For the edit form:
		actionProductFormBuilderModifier
		actionProductFormDataProviderData
		actionCategoryTreeSelectorFormDataProviderDefaultData
		actionCategoryTreeSelectorFormBuilderModifier
On the creation form:
		actionCreateProductFormDataProviderDefaultData
		actionCreateProductFormBuilderModifier

**Comment by zuk3975** [comment]
couldn't find where following hooks are executed:
 - displayCheckoutBeforeConfirmation

**Comment by thomasnares** [comment]
> couldn't find where following hooks are executed:
> 
> * displayCheckoutBeforeConfirmation

In classic theme : themes/classic/templates/checkout/_partials/steps/payment.tpl

```php
{hook h='displayCheckoutBeforeConfirmation'}
```

**Comment by thomasnares** [comment]
Not directly documented but generic ones, matched by regex in devdocs : 

- actionBeforeCreateCartSummaryFormHandler > generic
- actionAfterCreateCartSummaryFormHandler > generic
- actionBeforeCreateProductFormHandler > generic
- actionAfterCreateProductFormHandler > generic
- actionBeforeUpdateProductFormHandler > generic
- actionAfterUpdateProductFormHandler > generic

Missing ones : 

- displayBackOfficeEmployeeMenu
- actionProductFormBuilderModifier
- actionProductGridDefinitionModifier
- actionProductGridQueryBuilderModifier
- actionProductGridDataModifier
- actionProductGridFilterFormModifier
- actionProductGridPresenterModifier
- actionProductFormBuilderModifier
- actionProductFormDataProviderData
- actionCategoryTreeSelectorFormDataProviderDefaultData
- actionCategoryTreeSelectorFormBuilderModifier
- actionCreateProductFormDataProviderDefaultData
- actionCreateProductFormBuilderModifier

**Comment by thomasnares** [comment]
Created : 

- action<DefinitionId>GridDataModifier
- action<DefinitionId>GridDefinitionModifier
- action<DefinitionId>GridFilterFormModifier
- action<DefinitionId>GridQueryBuilderModifier
- action<FormName>FormBuilderModifier
- action<FormName>FormDataProviderData

Was already in : 

- displayBackOfficeEmployeeMenu

All done ✅
