### ISSUE TITLE
Switch doc 8 to 'current'

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#1562]
Now that PrestaShop 8 is live we need to update this:

![Capture d’écran 2022-10-27 à 09 13 06](https://user-images.githubusercontent.com/3830050/198215966-c31db1ff-c89a-45e7-a404-60bdf0a40be2.png)

@thomasnares I think the setting is here https://github.com/PrestaShop/devdocs-site/blob/main/src/config.yml#L29

**Comment by thomasnares** [comment]
Let me check that 👍

**Comment by marsaldev** [comment]
Hi @thomasnares,
I see previous (for 1.7) and current (for v8) on [devdocs](https://devdocs.prestashop-project.org/), can I close this Issue?

**Comment by thomasnares** [comment]
Yes, i did the change but forgot to close this issue, thanks
