### ISSUE TITLE
Check / test the documentation page for payment modules on V8

### ISSUE THREAD

**Issue by thomasnares** [PrestaShop/docs#1598]
An issue opened on the PrestaShop/PrestaShop repository indicates that the payment module page / examples is not working on v8. 

https://github.com/PrestaShop/PrestaShop/issues/30890

We have to check / test the examples on this page, and fix if the examples are broken

**Comment by dorian-b** [comment]
Can you consider this issue within the documentation?
ps_checkout not connecting to PayPal automatically on v8.0.2
https://github.com/PrestaShop/docs/issues/1629
Ping @PrestaShop/product-team & @PrestaShop/prestashop-core-developers

**Comment by thomasnares** [comment]
- [x] Works as intented on V8
- [x] Page refreshed on V8 doc
