### ISSUE TITLE
Update test section to encourage contributors to write / add unit tests.

### ISSUE THREAD

**Issue by FabienPapet** [PrestaShop/docs#1601]
Documentation is pointing to PHPUnit 5.7. And it has been pointed out that is it not clear enough.

That can stop developers to contribute because sometimes we want them to write unit test cases when possible. And the only documentation they have is this one.

https://github.com/PrestaShop/docs/blob/8.x/testing/unit-tests/how-to-create-your-own-unit-tests.md

**Comment by kpodemski** [comment]
Good idea! I think we could think about providing a list of examples.

Something like:

You create a configuration form, you can test it like this.
You create a new function in the Tools class and check the result like this.

We should probably think about PrestaShop-specific things too.

What do you think? How would you improve this part?

**Comment by FabienPapet** [comment]
Maybe some kind of guide about adding test values, with well written prs that can be added for examples like this one

https://github.com/PrestaShop/PrestaShop/pull/31006/files
