### ISSUE TITLE
PrestaShop 8.1 - list of items to be documented [wip]

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/docs#1602]
All elements:
https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+label%3A%22Needs+documentation%22+milestone%3A8.1.0+is%3Aclosed

Most of these elements are for the _Notable changes_ page with a short note.

- [x] https://github.com/PrestaShop/PrestaShop/pull/30415/files
changes related to translations

- [x] https://github.com/PrestaShop/PrestaShop/pull/29172
notable change, multi-statement queries are no longer allowed

- [x] https://github.com/PrestaShop/PrestaShop/pull/28752
extendibility of the product page, to be aligned with @jolelievre @zuk3975 

- [x] https://github.com/PrestaShop/PrestaShop/pull/30800
information about deprecation and a new path

- [x] https://github.com/PrestaShop/PrestaShop/pull/30588
examples that should go to the https://devdocs.prestashop-project.org/8/modules/concepts/services/#symfony-services 

- [x] https://github.com/PrestaShop/PrestaShop/pull/30510
change of the behavior, now if you delete a type, it deletes images

- [x] https://github.com/PrestaShop/PrestaShop/pull/30467
auto update of modules option is no longer available (we could think about integrating the setting into `ps_distributionapiclient`

- [x] https://github.com/PrestaShop/PrestaShop/pull/30408
just information that these things are now accessible from `$this->context->controller` or  front office` controller` in general

- [x] https://github.com/PrestaShop/PrestaShop/pull/30398
you can now get the default currency easier

- [x] https://github.com/PrestaShop/PrestaShop/pull/30383
new variable available, to be checked if it should go to the Themes documentation

- [x] https://github.com/PrestaShop/PrestaShop/pull/30347
update for the hook page

- [x] https://github.com/PrestaShop/PrestaShop/pull/30342 & https://github.com/PrestaShop/PrestaShop/pull/30314
info + there's a documentation about `{url}` that could be improved

- [x] https://github.com/PrestaShop/PrestaShop/pull/30163
deprecation warning

- [x] https://github.com/PrestaShop/PrestaShop/pull/29995
info + theme docs update

- [x] https://github.com/PrestaShop/PrestaShop/pull/29797
info about new hook + hook page

- [x] https://github.com/PrestaShop/PrestaShop/pull/29781
info about new hook + hook page

- [x] https://github.com/PrestaShop/PrestaShop/pull/29750
not sure if needed, this comment https://github.com/PrestaShop/PrestaShop/pull/29750#pullrequestreview-1125910115

- [x] https://github.com/PrestaShop/PrestaShop/pull/29516
new hooks + info about changing behavior of the contact module

- [x] https://github.com/PrestaShop/PrestaShop/pull/28541
info

- [x] https://github.com/PrestaShop/PrestaShop/pull/28469
BC Break in minor version

- [x] https://github.com/PrestaShop/PrestaShop/pull/28463
worth mentioning

- [x] https://github.com/PrestaShop/PrestaShop/pull/27927 - on hold
new hook

- [x] https://github.com/PrestaShop/PrestaShop/pull/27608
a notable change that this page is now multi-store compatible, it doesn't have bc breaks (constructor modifications are allowed)

- [x] https://github.com/PrestaShop/PrestaShop/pull/31004
new class to generate passwords

- [x] In `src/content/8/development/components/smarty-extensions/_index.md` we need to improve the `Replace any non-ASCII` part to `https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Tools.php#LL1416C30-L1416C30`

BC Breaks:
https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+milestone%3A8.1.0+label%3A%22BC+break%22+is%3Amerged

- [x] https://github.com/PrestaShop/PrestaShop/pull/28469
- [x] https://github.com/PrestaShop/PrestaShop/pull/28812
- [x] https://github.com/PrestaShop/PrestaShop/pull/29135

**Comment by thomasnares** [comment]
https://github.com/PrestaShop/docs/pull/1590

**Comment by thomasnares** [comment]
I think we are all good 👍

**Comment by kpodemski** [comment]
@thomasnares 
a few items left:
- hook details need to be updated: https://github.com/PrestaShop/PrestaShop/pull/29499
- new hook since 8.1: https://github.com/PrestaShop/PrestaShop/pull/28999 - notable changes + hook docs
- information to the notable changes: https://github.com/PrestaShop/PrestaShop/pull/29314
- hook details to update: https://github.com/PrestaShop/PrestaShop/pull/31620/files
- notable changes, information about a new library being included to the core: https://github.com/PrestaShop/PrestaShop/pull/30225

**Comment by thomasnares** [comment]
https://github.com/PrestaShop/docs/pull/1688/files

✅
