### ISSUE TITLE
ps_checkout v3.0.2 for 8.0.2 - PayPal error

### ISSUE THREAD

**Issue by dorian-b** [PrestaShop/docs#1629]
Hi,
I am being redirected after setting up paypal to: a [https://checkout-api-live.prestashop.com/configuration .. page
Error: code 400
“"merchantIdInPayPal must be a string, merchantIdInPayPal should not be empty, merchantId must be a string"
I am using the latest PrestaShop and latest "ps_checkout" module,
the PayPal module v5.7.7 "paypal" works fine connecting to paypal business. 
Is this an issue with setting up an API or is there something wrong with the ps_checkout module?
I am used to simply connecting to PayPal and not creating an API on the PayPal developer site ...
I tried to downgrade the module version, 
v2.21.0 = can't connect to PrestaShop, so PayPal step couln't be achieved, probably because I have a PrestaShop 8.x.x version installed.
ps_checkout-3.0.1 = currently checking it out ... Update: same issue as with v3.0.2

**Comment by kpodemski** [comment]
Hello @dorian-b 

It would be better to contact the team responsible for PrestaShop Checkout in PrestaShop SA. Open-source project members don't work on this module.
