### ISSUE TITLE
Improve homepage of the documentation

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/docs#1648]
We have some unused space on the developer documentation homepage. This is what we can do:

1. Two new sections:
- recommended to read
- most popular pages
- remove spacing/font sizes in the first paragraph to make these two sections visible when visiting the docs.

2. Some other improvements
- change the URL of [Learn more about PrestaShop project](https://www.prestashop.com/). to [Learn more about PrestaShop](https://www.prestashop-project.org/).
- there should be a link to the developer's blog somewhere
- also, we could have a link to the top contributors' site - maybe those two should be on the left?

**Comment by thomasnares** [comment]
Add to footer: 

- CTA to contribute to docs
- Still need help? section with links to Slack, Github discussions

Maybe add : 

- Voting widget (with service to handle results)
