### ISSUE TITLE
Somes search of hook name show another one

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/docs#1654]
<img width="642" alt="Capture d’écran 2023-05-06 à 15 46 01" src="https://user-images.githubusercontent.com/2631425/236628096-36c6237b-8806-491c-a0b9-8e5ab34887eb.png">

**Comment by thomasnares** [comment]
Hi @PrestaEdit , this is inherent of the way our hook regex matching works to maybe make false positives. 

We can update the matched hook to `actionAdmin<ControllerName><Action>Before` to fix the false positive. 

But, which hook should have been returned for your example `actionProductSearchProviderRunQueryBefore` ?

**Comment by thomasnares** [comment]
Need to Document :

> actionProductSearchProviderRunQueryBefore (classes/controllet/ProductListingFrontController.php)
> actionProductSearchProviderRunQueryAfter (classes/controllet/ProductListingFrontController.php)

**Comment by thomasnares** [comment]
Looks like they were already documented: 

https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/actionproductsearchproviderrunquerybefore/

https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/actionproductsearchproviderrunqueryafter/

**Comment by thomasnares** [comment]
But only in V8, not in 1.7

**Comment by kpodemski** [comment]
As the hooks page has been improved drastically on the v8 page, we won't be backporting changes to 1.7 anymore.

If you notice something to improve in v8 version let us now @PrestaEdit 💪🏻 or maybe submit a PR 👀
