### ISSUE TITLE
Broken link in 8/modules/core-updates/8.0/

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#1660]
Broken link in https://devdocs.prestashop-project.org/8/modules/core-updates/8.0/

Line `Due to the new password policy management features, third-party solutions that generate customer data might require to implement changes accordingly.`

But when I look at the code it seems valid 😮 https://raw.githubusercontent.com/PrestaShop/docs/8.x/modules/core-updates/8.0.md

```
[new-password-policy]: {{< relref "8/modules/core-updates/new-password-policy" >}}
```

**Comment by boherm** [comment]
It seems to be fix a minute ago https://github.com/PrestaShop/docs/pull/1659#event-9219820049 :-D

**Comment by thomasnares** [comment]
I infiltrated your brain @matks

**Comment by matks** [comment]
😱
