### ISSUE TITLE
Bad links to theme templates

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/docs#1702]
`Located in:` links have old links to TPLs. Theme has been moved to separate repo, we need to update it. ;-)

**Example:**
https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/displaygdprconsent/

**404:**
https://github.com/PrestaShop/PrestaShop/blob/8.0.x/themes/classic/modules/ps_emailsubscription/views/templates/hook/ps_emailsubscription.tpl

**Comment by kpodemski** [comment]
@thomasnares let's treat it with higher priority 👍🏻 

`Classic` has been moved to its own repository: https://github.com/PrestaShop/classic-theme
