### ISSUE TITLE
Few FO hooks are not listed in the dev doc

### ISSUE THREAD

**Issue by ElodieOS** [PrestaShop/docs#1717]
I've found a few FO hooks that aren't listed in the devdoc. However, some of them exist and can be used in the transplant module list. I have noted this list :

- displayProductButtons
- graphEngine
- gridEngine
- paymentReturn
- displayContactRightColomn
- displayAdminOrderBottom
- displayAdminOrderTabOrder
- displayAdminOrderTabShip
- displayAdminOrderTop
- displayAdminOrdersListAfter
- displayAdminStatsGraphEngine
- displayAdminStatsGridEngine
- displayAttributeForm
- displayAttributeGroupPostProcess
- displaybackOfficeFooter
- displaybackOfficeHome
- displaybackOfficeOrderActions
- displayContentWrapperBottom
- displayContentWrapperTop
- displayFeatureValueForm
- displayHeaderCategory
- displayModuleConfigureExtraButtons (BO)
- displayNav
- displayPDFInvoice
- displayProductExtraContent
- displayWrapperBottom
- displayWrapperTop

**Comment by Hlavtox** [comment]
Good job @ElodieOS 🎉

Beware that some of them may be deprecated - paymentReturn for example?

I had a tool somewhere that scanned the code for hooks and compared it with devdocs and database, I will try to find it. :-)

**Comment by ElodieOS** [comment]
Thank you @Hlavtox! 

Oh it will be perfect if you have a tool like this yes! Indeed, I think some of them would be deprecated

**Comment by thomasnares** [comment]
also Missing :

- gridEngine
- graphEngine

**Comment by PululuK** [comment]
see https://github.com/PrestaShop/docs/issues/1540

**Comment by thomasnares** [comment]
| Missing item | Information | Link |
| --- | --- | --- |
| displayProductButtons | created | https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/displayproductbuttons/ |
| graphEngine | aliased to displayAdmonStatsGraphEngine | https://github.com/PrestaShop/docs/pull/1733 |
| paymentReturn | renamed to displayPaymentReturn | https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/displaypaymentreturn/ |
| displayContactRightColomn | typo in your list, it is **displayContactRightColumn** | https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/displaycontactrightcolumn |
| displayAdminOrderBottom | This one is listed in hook.xml but never rendered |  |
| displayAdminOrderTabOrder | deprecated from **1.7.7** |  |
| displayAdminOrderTabShip | deprecated from **1.7.7** |  |
| displayAdminOrderTop | fixed | https://github.com/PrestaShop/docs/pull/1733 |
| displayAdminOrdersListAfter | Unable to find any valid reference to this one |  |
| displayAdminStatsGraphEngine | created | https://github.com/PrestaShop/docs/pull/1733 |
| displayAdminStatsGridEngine | created | https://github.com/PrestaShop/docs/pull/1733 |
| displayAttributeForm | created | https://github.com/PrestaShop/docs/pull/1733 |
| displayAttributeGroupPostProcess | needs some work to be integrated (ps_faceted_search) |  |
| displaybackOfficeFooter | deprecated from **1.7.7** |  |
| displaybackOfficeHome | deprecated from at least 1.6.x |  |
| displaybackOfficeOrderActions | aliased to displayAdminOrderSide |  |
| displayContentWrapperBottom | created |  |
| displayContentWrapperTop | created |  |
| displayFeatureValueForm | created | https://github.com/PrestaShop/docs/pull/1733 |
| displayHeaderCategory | created | https://github.com/PrestaShop/docs/pull/1733 |
| displayModuleConfigureExtraButtons | created | https://github.com/PrestaShop/docs/pull/1733 |
| displayNav | use displayNav1 or displayNav2 for classic derived themes |  |
| displayPDFInvoice | created |  |
| displayProductExtraContent | created | https://github.com/PrestaShop/docs/pull/1749 |
| displayWrapperBottom | created |  |
| displayWrapperTop | created |  |

**Comment by thomasnares** [comment]
Related PR to fix missing `displayProductButtons` : https://github.com/PrestaShop/ps-docs-theme/pull/45

**Comment by thomasnares** [comment]
all done 👍
