### ISSUE TITLE
There are some errors between the BO and FO hooks in the dev doc

### ISSUE THREAD

**Issue by ElodieOS** [PrestaShop/docs#1718]
I could be wrong, but I think there are some errors between the BO and FO hooks in the list of hooks. These hooks are not FO hooks as indicated in the devdoc but BO hooks: 

- displayDashboardToolbarTopMenu
- displayDashboardTop
- displaybackOfficeEmployeeMenu
- graphEngine
- gridEngine

**Comment by Hlavtox** [comment]
You are right, all of them belong to BO. :-)

**Comment by thomasnares** [comment]
fixed the 3 display* hooks, i have to create pages for graphEngine / gridEngine, but i will do that in #1717
