### ISSUE TITLE
Adding a configuration page with Symfony forms

### ISSUE THREAD

**Issue by OlenaTSaruk** [PrestaShop/docs#1734]
I followed all the described steps, but it does not work and gives an error with debugger.
https://devdocs.prestashop-project.org/8/modules/creation/adding-configuration-page-modern/

Module 'demosymfonyformsimple' doesn't work either.

**Comment by thomasnares** [comment]
Hello @OlenaTSaruk , can you tell me what kind of message the debugger is indicating?

**Comment by OlenaTSaruk** [comment]
1. https://tinypic.host/image/f6ovH
But I have ContactConfigurationController

2. https://tinypic.host/image/f6EqR for 'demosymfonyformsimple'

**Comment by thomasnares** [comment]
Did you ran `composer dump-autoload` from within the module folder ? As indicated here : https://devdocs.prestashop-project.org/8/modules/creation/adding-configuration-page-modern/#create-the-base-module

```
Then, run composer dump-autoload from the module’s directory to generate the autoload.php file. See [Setup composer in a module](https://devdocs.prestashop-project.org/8/modules/concepts/composer/#autoloading) for more informations.
```

**Comment by OlenaTSaruk** [comment]
I ran composer dump-autoload, but the error persists:
"The controller for URI "/modules/contactformimg/configuration" is not callable: Controller "PrestaShop\Module\ContactFormImg\Controller\ContactConfigurationController" does neither exist as service nor as class."

**Comment by OlenaTSaruk** [comment]
logs:
https://tinypic.host/image/f6wZa

stack:
https://tinypic.host/image/f6F6Q

**Comment by kpodemski** [comment]
@OlenaTSaruk could you send us a full module?

**Comment by kpodemski** [comment]
also, I'm transferring this issue to the Q&A section of Github Discussions 👍🏻

**Comment by kpodemski** [comment]
Since we have had no news from you for more than 20 days, I'm closing this Issue.
