### ISSUE TITLE
Cannot download language pack "en"

### ISSUE THREAD

**Issue by JQJoe** [PrestaShop/docs#1788]
Create file parameters
Create database tables
Create default shop and languages
An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by [clicking here](http://192.168.31.2:18888/install/index.php?restart=true).

1: 0
Cannot download language pack "en"

**Comment by kpodemski** [comment]
Hello @JQJoe 

I think it might be related to your server configuration. Apart from that, this repository contains PrestaShop developer documentation. If you want to report a bug problem, it's better to do it [here](https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=Bug%2CNew&projects=&template=1_bug_report.yml).

Although, like I wrote, I think this is something related to your server configuration that is not able to download localization pack.
