### ISSUE TITLE
Document issue priority levels

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/docs#199]
Here's a good source of inspiration:

https://www.drupal.org/core/issue-priority

**Comment by matks** [comment]
Answers are here http://build.prestashop.com/news/severity-classification/ we need to migrate this into the doc

**Comment by eternoendless** [comment]
Related: Copy in docs the content of Severity blog article #289

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/docs/pull/360
