### ISSUE TITLE
Explain how to manage Tabs registering with symfony routes

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/docs#210]
The Tab don't manage Symfony routes, so in order to add such tabs you need to hack a little:
- you need to have a `_legacy_link` on your route and use it as your `class_name` parameter
- you must add your Tab mannually (using `new Tab`)

This hack needs to be documented, unless https://github.com/PrestaShop/PrestaShop/issues/12640 has been managed in the 176.

**Comment by mickaelandrieu** [comment]
would you mind to document the hack and the new way to do in 1.7.6?

I know this question has been already asked here (in the issues) and on the forum.

This can be a short paragraph with a link to a demonstration module (we could move it into the "friends-of-prestashop" organization).

WDYT?

**Comment by jolelievre** [comment]
Yes, it is planned to be done before the 1.7.6 goes out. I add this issue to the backlog to be sure not to forget it.

**Comment by jolelievre** [comment]
Done by https://github.com/PrestaShop/docs/pull/300
