### ISSUE TITLE
Documentation about carrier modules

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/docs#222]
We currently have documentation about payment modules, but not about carriers.

Example of details to give:

### In case of several carriers created by the same module, how to differentiate their price during `getOrderShippingCost` ? 

By declaring the property `id_carrier` in the module, and relying on it in the method.

```php
class MyModule extends CarrierModule
{
   /**
    * @var int Current ID carrier in shipping cost calculation
    */
    public $id_carrier;

    public function getOrderShippingCost(...)
    {
        if ($this->id_carrier === /* ID of one of the module carriers */) {
            // Specific calculation for one carrier
        }
    }
}
```

**Comment by TechhDan** [comment]
It's almost a year since this was posted. Is there any plans to create Carrier documentation? I'm developing a carrier module but I'm a bit stuck :( help!

**Comment by toutantic** [comment]
This quetion/answer should go here:
https://devdocs.prestashop.com/1.7/faq/shipping/

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/docs/pull/979
