### ISSUE TITLE
Deploy an online version of the doc for each pull request

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/docs#225]
So, it's easier to review and spot every error for each contribution.

There are many ways to do it, but this is a documented one => https://medium.com/akeneo-labs/how-platform-sh-can-simplify-your-contribution-workflow-on-github-6e2a557a1bcc

**Comment by matks** [comment]
Hi @mickaelandrieu I dont think it's an issue for the doc, is it ? 😅It's rather a github tooling / github integration issue ?

**Comment by eternoendless** [comment]
I think he means this for people who don't want to run hugo on their own computer.

**Comment by matks** [comment]
Oooooh 😄got it !
