### ISSUE TITLE
Question: are we able to use community modules in the official docs?

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/docs#235]
As spotted in some contributions already, it could be great for everyone to be able to download some modules linked to the tutorials in the documentation.

Also, I'm thinking about a page where people can contribute to and share good community resources.

So my question is the following: are we able to mention and use community modules and resources in the documentation?

Mickaël

**Comment by eternoendless** [comment]
The answer is yes but they should be in a PrestaShop or PrestaShop-affiliated repository in order to prevent them from disappearing or fall out of sync with the documentation.
