### ISSUE TITLE
Add doc about staging / production setup

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#238]
I get more and more questions about how the best way to handle a staging environment and a production environment for a PrestaShop, all of it versioned into git.

Additionnal questions are:
- how to handle upgrades using git*
- how to setup continous integration
- how to setup continuous deployment

*Several developers asked the following:
"I have a staging environment and a production environment.
If I run the auto-upgrade module on staging, this will upgrade both the code and the database of staging. Then I commit the new file structure into git. However if I pull these changes into production, I have in production an environment with up-to-date code but outdated database."

⏩ the real issue is actually "how to handle database upgrade and code upgrade separately"

Another issue which is kinda related: some developers wonder whether they should use the release zip archive of the github release tag:

**The release zip archive** contains a zipped ready-to-use prestashop application however if the developer wishes to develop on top of it, it lacks some dev features such as the tests, the composer.json file ...

**The release tag on github** has all of these dev tools but need some processing to be production-ready.

**Comment by jf-viguier** [comment]
Yes, it's a main concern. I'm looking forward to reading it.

**Comment by PierreRambaud** [comment]
>The release zip archive contains a zipped ready-to-use prestashop application however if the developer wishes to develop on top of it, it lacks some dev features such as the tests, the composer.json file ...

This one is production ready, if you want to be able to use dev features, you must use the "From source" method. It's not relevant to change this kind of behavior. It's really better to add doc to explain to the devs how to use git instead.

> The release tag on github has all of these dev tools but need some processing to be production-ready.

This is why we called it "From source", you always need to download dependencies, on each tools, each programs, it's totally legit.

**Comment by matks** [comment]
Yes, I think https://github.com/PrestaShop/PrestaShop/issues/14086 is now a better topic covering that

**Comment by matks** [comment]
## Idea to test

Choose the "full git" solution: put in git all developer files, use a .gitignore to avoid versioning the folders containing assets, logs, cache...

#### What happens when there is a PS upgrade or a module/theme install/upgrade ?

You need a build environment, which can be the staging/pre-production server. If we use it like this:

1) On build env, both code and database are up-to-date. Git latest commit is a123tbc.
2) Perform the install/upgrade
3) Commit to save the new state of the code into git. New commit zyx789tcb.

At this moment, if we deploy/checkout in production, we'll have the codebase being updated without the database schema and content modified. In orde to complete the deployment, we need to *re-apply all database changes that happend on build env into prod env*.

The idea is to use [Doctrine Migrations](https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/).

Doctrine Migrations is able to perform a diff between a Doctrine database configuration and the real database schema. And using this diff, it can generate a SQL script to make the schema comply with the configuration.
https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html#generating-migrations-automatically

If we are able to make Doctrine read the ObjectModel configuration instead of its usual mapping, we should be able to **automatically generate the required SQL script to update the database**.

Then, we'd apply the standard usage of Doctrine Migrations: store it as a Migration, be able to run/rollback on any environment.
https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html#usage
The scripts in `install-dev/upgrade/sql/` kind of mimic this system, but they are generated manually.

So if I complete the initial deployment procedure:

1) On build env, both code and database are up-to-date. Git latest commit is a123tbc.
2) Perform the install/upgrade
3) Run PrestaShopDoctrineMigrationsBridge (name can be improved) to generate a database Migration-DDMMYYYY.sql .
4) Commit to save the new state of the code into git. New commit zyx789tcb. Git has stored the SQL script.
5) Put prod env shop in maintenance mode.
6) Deploy in prod environment the new codebase, revision zyx789tcb. Database is not yet updated.
7) Run Migration-DDMMYYYY.sql
8) Deploy is complete !

The cool thing ? If we find out that there is something nasty in production, we can rollback to previous version a123tbc using Doctrine Migrations ability to rollback.

**Comment by jf-viguier** [comment]
It sounds good, but it's a lot of changes.
Another way is implementing the same upgrade macanism of modules for the core : if version number is greater, Prestashop launch upgrade script(s) that can execute sql. What do you thing ?

**Comment by matks** [comment]
> It sounds good, but it's a lot of changes.
> Another way is implementing the same upgrade macanism of modules for the core : if version number is greater, Prestashop launch upgrade script(s) that can execute sql. What do you thing ?

This requires that a module is able to detect that the database schema it uses is not used. Like "code is using v3.4 but database uses v3.2".
DoctrineMigration has a very simple solution for this: they add a SQL table where they store the version number so the code can check whether database is up-to-date by performing a SELECT query to the table.

But right now PS has no ways to know which modules are up-to-date and which modules are outdated 🤔

**Comment by Quetzacoalt91** [comment]
> But right now PS has no ways to know which modules are up-to-date and which modules are outdated thinking

Are you sure about that? The "installed" version of the module is stored in the database table ps_modules. If the files have been updated, PrestaShop knows an update must be run, at least to upgrade the version in the database.

**Comment by matks** [comment]
> > But right now PS has no ways to know which modules are up-to-date and which modules are outdated thinking
> 
> Are you sure about that? The "installed" version of the module is stored in the database table ps_modules. If the files have been updated, PrestaShop knows an update must be run, at least to upgrade the version in the database.

Works indeed if module performs a real upgrade, with a version number.

It will not work if the module is a custom module made for this shop by the developer, but this is a side-case we can address later.

So ... it seems to be great 😄

**Comment by jf-viguier** [comment]
If a custom module doesn't change his number and doesn't make a upgrade script : it's his concern. It shouldn't be a prestashop concern.

For the core, is this sql files are ok ? https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/upgrade/sql 
They should be used by the "database only" upgrade.
What do you think ? 
The 1click upgrade should already have this code somewhere.

**Comment by matks** [comment]
I close this because I will never find the time to do it (see https://github.com/PrestaShop/PrestaShop/issues/14086 for details) 😢
