### ISSUE TITLE
Improve menu navigation

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/docs#241]
Current menu structure is more or less weird, it seems that topics are randomly put in any location that seems "most appropriate".

Some rules should be defined:
1. What is "Core development"? What can be considered as "Core development"? What should be at the root of this section? Same for "Modules" and "Themes" sections.

My suggestion for menu (it's more like "big picture" without much details):
1. Basics
    * Introduction
    * Installation 
2. Core development
    * Standards & conventions
        * Coding standards
        * Naming conventions
    * Architecture
    * Components
        * Grid
    * Testing
        * Unit tests
        * BDD tests
        * E2E tests
    * CLDR
    * Database
    * Webservice
2. Module development
    * Getting started
        * Legacy Admin controllers
        * Symfony admin controllers
        * Front controllers
    * Testing
    * Hooks
    * Payment modules
    * Shipping modules
3. Theme development
    * Getting started
4. Contribute
    * Code
    * Documentation
5. Cookbook (Scale previously)
    * Optimization
        * How to benchmark PrestaShop?
        * How to optimize PrestaShop?

Some things that could be improved:
1. Core changes should not be under "Modules" section. Maybe there should be "Changelog" as separate section to document BC breaks & most notable changes (just an idea).
https://prnt.sc/n9xd6y

2. I think that "Documentation" section should not be part of Documentation itself. It's mainly about contributing to Docs, so I think it should be moved under "Contribute".
https://prnt.sc/n9xl50

3. There should not be "How tos" at the root of "Core development". These are very small topics thus should be under some subsection, for example "Cookbook", like:
* Cookbook
    * Email
        * How to send e-mails?

    https://prnt.sc/n9xo72

4. Side menu levels are not easy to follow. Maybe styling should be improved or maybe dropdowns added, not sure. :/
https://prnt.sc/na0xrm

**Comment by sarjon** [comment]
@matks can you take a look at this issue? I was navigating through menu it for me, it's such a mess. :/ Do you think we can improve it?

**Comment by matks** [comment]
@eternoendless wdyt ? 😄

**Comment by tomas862** [comment]
seems better structure for me as well :+1:

**Comment by sarjon** [comment]
ping :ping_pong: @eternoendless :ping_pong: pong

**Comment by eternoendless** [comment]
I agree that the structure is not optimal, give me some time to think about it.

Regarding the tree, I also agree that navigation is suboptimal but I haven't had time to add dropdowns. This could be achieved by adding a little javascript as the complete tree structure is rendered by Hugo in all pages, the rest is just a little CSS. If you would contribute a PR for that I would gladly merge it ;)

**Comment by matks** [comment]
> I also agree that navigation is suboptimal but I haven't had time to add dropdowns

this has been done
