### ISSUE TITLE
ToggleColumn wrong parameter

### ISSUE THREAD

**Issue by Payalba** [PrestaShop/docs#258]
Hi,

I think the name of the option property 'route_param_name' in ToggleComumn Type  (https://devdocs.prestashop.com/1.7/development/components/grid/columns-reference/toggle/) is wrong

The good options property  is 'route_param_id'

Regards,

PYT

**Comment by matks** [comment]
Hi @Payalba according to the source file, it really is `route_param_name`:
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Grid/Column/Type/Common/ToggleColumn.php

**Comment by Payalba** [comment]
The name changed between 1.7.5 and 1.7.6 ?
But the doc for the 1.7.5 say "route_param_name" and it is route_param_id in the 1.7.5 version.

**Comment by matks** [comment]
You are right. Congratulations you spotted a real issue 😉 

I opened https://github.com/PrestaShop/PrestaShop/issues/13544 to solve it, then we can fix the doc accordingly

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14027
