### ISSUE TITLE
Update theme articles as Starter Theme is now deprecated

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#273]
https://devdocs.prestashop.com/1.7/themes/getting-started/starter-theme/

Starter Theme is now deprecated so we should update the doc items to talk either about the Classic Theme or maybe the promising https://github.com/PrestaShop/classic-rocket

**Comment by DrMechanica** [comment]
Hey, any word on this? I'd really like to make my own theme, but not sure where to start at this point.

**Comment by matks** [comment]
@DrMechanica we're 90% sure we're going to promote Classic Rocket theme instead of Starter Theme, so you can use it as a starting point 😉

**Comment by DrMechanica** [comment]
@matks Awesome. Thanks man.

**Comment by prestaforum** [comment]
🆙 
I started using StarterTheme then read about it being deprecated. It would be very nice to make it more clear in the documentation.
