### ISSUE TITLE
how to load custom js and css

### ISSUE THREAD

**Issue by smartdatasoft** [PrestaShop/docs#28]
Hello, how to load custom css and js only from that hook execute. Like in the past if any one want to load js and css from a dynamic hook they didn't load.

```
<div id="footer">
  {widget name="ps_contactinfo" hook="displayFooter"}
</div>


```

The goal of this is load different js and css from different widget area, one from home another for special in footer.

**Comment by julienbourdeau** [comment]
Hi @smartdatasoft,

I updated the documentation about assets: http://developers.prestashop.com/themes/assets/index.html

Also I think at this time of execution, CSS and JavaScripts are already sent to Smarty (and even printed) so there is no way to do this.

I believe it won't be a lot of code so you can probably bundle it in one file.
