### ISSUE TITLE
memcached yes ot not

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/docs#292]
Prestashop 1.7.5.2 on debian with php 7.2.19
Version MySQL: 10.1.38-MariaDB-0+deb9u1
As I read here (https://devdocs.prestashop.com/1.7/scale/optimizations/#6-optimize-your-prestashop) you suggest to NOT enable the cache feature. It's right for me with my mysql version?
Thank you

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by matks** [comment]
@PierreRambaud @djodjo3 do you have an opinion ?

**Comment by PierreRambaud** [comment]
Since you're using 10.1.38-MariaDB-0+deb9u1 you must not enable the cache. 
If you need more details about your MySQL version use this sql query:
```sql
SHOW VARIABLES LIKE "%version%";
```
You'll able to see your innodb version. But as I know, MariaDB backport only feature from MySQL 5.6 and 5.7.
