### ISSUE TITLE
Add docs about docker official prestashop images

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#296]
We should explain what https://github.com/PrestaShop/docker contains and what is being maintained

**Comment by Quetzacoalt91** [comment]
We currently have in the documentation an introduction to our Docker images: https://devdocs.prestashop.com/1.7/modules/testing/

As each one is a link to a Readme, what else do you expect?

**Comment by matks** [comment]
My bad. I checked https://devdocs.prestashop.com/1.7/contribute/contribute_using_docker/ , 
https://devdocs.prestashop.com/1.7/modules/sell/technical-tools/ , and
https://devdocs.prestashop.com/1.7/contribute/ but not this one.

You're right, this is more than enough 👍

**Comment by matks** [comment]
(actually, I did not check the article although I saw it in devdocs search bar because I saw it was in the "testing" section, maybe we can add another link, some "deploy" section in order to help people willing to use docker in production to find it)

**Comment by Quetzacoalt91** [comment]
Reopening because of the information misplaced
