### ISSUE TITLE
Typo in JavaScript events

### ISSUE THREAD

**Issue by PrestaShark** [PrestaShop/docs#302]
Hi.
There is no updateFaces event in the entire Prestashop 1.7...
Mentioned in https://devdocs.prestashop.com/1.7/themes/reference/javascript-events/

There is updateFacets event! ;)

This can be misleading

PS. Funny is that also BELVG mention about "updateFaces" in https://belvg.com/blog/comparing-javascript-in-prestashop-1-7-and-1-6.html

**Comment by eternoendless** [comment]
Fixed, thanks!
