### ISSUE TITLE
[Services] Explain how to redefine/override a Symfony service ?

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/docs#318]
This [article](https://devdocs.prestashop.com/1.7/modules/concepts/services/) is missing this part:

- find the related service using `debug:container` command ;
- implements the interface if any ;
- in the module redefine the service ;
- check that the service is now the one we have defined ;

WDYT?

Docs:

* [Service override](https://symfony.com/doc/3.4/service_container.html#fetching-and-using-services)
* [Service decoration](https://symfony.com/doc/3.4/service_container/service_decoration.html)

**Comment by jf-viguier** [comment]
Yeah man

**Comment by sarjon** [comment]
Decoration could also be an option in some cases. :)

https://symfony.com/doc/3.4/service_container/service_decoration.html

**Comment by mickaelandrieu** [comment]
totally @sarjon !

**Comment by nicoja** [comment]
yes !

**Comment by olecorre** [comment]
yes !

**Comment by SebBareyre** [comment]
Need too :)

**Comment by matks** [comment]
Should be fixed by https://github.com/PrestaShop/docs/pull/334

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/docs/pull/334
