### ISSUE TITLE
Document how to get internal links

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/docs#328]
Document how to get links to internal pages:

- Front page
- BO pages (legacy and Sf)
- Module pages (FO and BO)

**Comment by matks** [comment]
And document how to get/compute these links in both legacy and Symfony context

Links including POST and DELETE statements ?

**Comment by kpodemski** [comment]
@thomasnares 

We could take this task as a quick improvement.

1. I think we could have an internal linking between the "Link component" and how to generate SF Links. We could add a section on how to link to BO pages. https://devdocs.prestashop-project.org/8/modules/concepts/controllers/admin-controllers/route-generation/#using-router-via-link-getadminlink
2. There's also a problem with this notice:
https://capture.dropbox.com/GoANIUZG6KVe1wxY
3. Double-quotes to single-quotes in Link component docs :)

**Comment by thomasnares** [comment]
Fixed by : https://github.com/PrestaShop/docs/pull/1668
