### ISSUE TITLE
Wrong Link for TranslateTextType in doc

### ISSUE THREAD

**Issue by nenes25** [PrestaShop/docs#349]
Hi,

On page https://devdocs.prestashop.com/1.7/development/components/form/types-reference/ the link to the "TranslateTextType" returns a 404 error.

According to the code source this class is deprecated since PS 1.7.6.
So I don't know if the link has be to be removed or if a content is missing ( as nothing seems to match with this type in directory src/content/1.7/development/components/form/types-reference )

Regards,

**Comment by matks** [comment]
Thanks @nenes25 for the link, you're right, and I noticed "TranslateType" reference gets 404 too

> So I don't know if the link has be to be removed or if a content is missing ( as nothing seems to match with this type in directory src/content/1.7/development/components/form/types-reference )

As we follow SemVer, I guess we'll keep the content but strongly suggest to use TranslatableType instead

**Comment by jf-viguier** [comment]
TranslateTextType class is explicit "since version 1.7.6 and will be removed in 1.8. Use the TranslatableType instead"
I suggest to remove TranslateTextType from the doc page.

**Comment by matks** [comment]
Bu what about people using a 1.7.5 shop ? They might find it useful 😄

**Comment by jf-viguier** [comment]
@matks do you means that the TranslateType way wasn't available in 1.7.5 ?
May be the doc should mention "deprecated, use TranslateType instead" ?

**Comment by PrestaEdit** [comment]
There is no more link on it and it's mention that it's deprecated, already.
