### ISSUE TITLE
Module invalid token

### ISSUE THREAD

**Issue by monumatik** [PrestaShop/docs#357]
Hi, i'am a new in PS.
I try to create my own module in PS and i do it according to following guide:
https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/

I created module and successfully installed, but when i try to go to module url i got 'Invalid token' warning. Are you able to help me ? Maybe it's an issue :)

**Comment by khouloudbelguith** [comment]
Hi @monumatik,

>but when i try to go to module url i got 'Invalid token' warning. 

When navigating to the module configuration page => an invalid token is displayed?

Thanks!
