### ISSUE TITLE
Add displayPayment to Hook list

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/docs#387]
"displayPayment" hook is used to set the order of the payment modules.

And surely for more things.

Please document this and other similar payment hooks.

**Comment by Quetzacoalt91** [comment]
This repository contains documentation for PrestaShop 1.7+.
This hook has been removed on PS 1.7 and replaced by `hookPaymentOptions`.

**Comment by davidglezz** [comment]
Then there is much more to document:
- Document that hook exists (used in previous versions and deprecated in 1.7)
- Prestashop 1.7.6.1 still using `DisplayPayment` for compatibility. https://github.com/PrestaShop/PrestaShop/search?q=displayPayment&unscoped_q=displayPayment
- `paymentOptions` is not documented in [list-of-hooks](https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/), only in [Payment modules](https://devdocs.prestashop.com/1.7/modules/payment/)
- The new hook `paymentOptions` is misleading because it is an invisible hook but has an effect on something visual.
- In addition, `displayPayment` (old) has a higher priority than `paymentOptions` (new) when ordering (Hook Position) payment methods. The opposite for the rendered content (First, Prestashop try to call `paymentOptions`, then `displayPayment`)

@Quetzacoalt91 @PierreRambaud

**Comment by davidglezz** [comment]
Why not reopen this issue?
