### ISSUE TITLE
Optimizations docs page recommends a lower table_open_cache value than the default

### ISSUE THREAD

**Issue by Gamesh** [PrestaShop/docs#428]
optimizations page says to set `table_open_cache = 1000`
https://devdocs.prestashop.com/1.7/scale/optimizations/#5-mysql-mariadb-settings

while the default of MySQL is **2000** for MySQL <8.0.3 and **4000** for MySQL >8.0.4
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_table_open_cache

is this intentional or a mistake, perhaps a recommended value should be higher than the minimum default?

**Comment by matks** [comment]
Hi @Gamesh I guess this part of the doc has been written a very long time ago. For example according to https://mariadb.com/kb/en/optimizing-table_open_cache for versions < 10.1.7 of MariaDB default value was 400.

@PierreRambaud I suggest we update these numbers to use MySQL 5.6 or MysQL 5.7 default value when it's higher than what the documentation mentions, wdyt?

**Comment by PierreRambaud** [comment]
> Hi @Gamesh I guess this part of the doc has been written a very long time ago. For example according to https://mariadb.com/kb/en/optimizing-table_open_cache for versions < 10.1.7 of MariaDB default value was 400.
> 
> @PierreRambaud I suggest we update these numbers to use MySQL 5.6 or MysQL 5.7 default value when it's higher than what the documentation mentions, wdyt?

The problem with optimization is it depends on the system and software versions you are using.

This is why this sentence has been added.

> As always, these values should be adjusted to your own environment, you probably won’t need a host_cache_size of 1000

AFAIK, these optimizations has been added by @jocel1 , he's the best one to answer what's the best :+1:

**Comment by jocel1** [comment]
Hi! 

Usually prestashop doesn't need more than 1000 for the table_open_cache, but with a lot of modules it could be useful. Since having a value of 4000 doesn't have any drawback I would suggest updating the documentation to use table_open_cache=4000 :)

**Comment by matks** [comment]
Update done by @kpodemski
