### ISSUE TITLE
Add the 1.7 database schema

### ISSUE THREAD

**Issue by xBorderie** [PrestaShop/docs#43]
Just as we did for previous version:

* http://doc.prestashop.com/display/PS14/Fundamentals#Fundamentals-Databaseschema
* http://doc.prestashop.com/display/PS15/Fundamentals#Fundamentals-Databaseschema
* http://doc.prestashop.com/display/PS16/Fundamentals+of+PrestaShop+Development#FundamentalsofPrestaShopDevelopment-Databaseschema

**Comment by mickaelandrieu** [comment]
https://github.com/PrestaShop/docs/pull/115
