### ISSUE TITLE
Prestashop 1.7 error generated during the multistore mode.

### ISSUE THREAD

**Issue by davinderesfera** [PrestaShop/docs#44]
when Logistician user try to configure module for his own store then this error is generated
 

SmartyException in smarty_internal_templatebase.php line 129: Unable to load template file =>inside admin folder ==>'/themes/default/template/content-legacy.tpl'

url for the regeneration ==> /index.php?controller=AdminModules&configure=googleshopping&token=

**Comment by xBorderie** [comment]
Please report this issue in the Forge: http://forge.prestashop.com/secure/CreateIssue%21default.jspa?selectedProjectId=11322&issuetype=1
Thank you!
