### ISSUE TITLE
Add doc about Tab route_name field

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/docs#458]
A new feature has been added in Tab to allow using a route_name instead of a controller
https://github.com/PrestaShop/PrestaShop/issues/12640

This needs to be documented:
- new route_name in tab
- improvement of automatic Tab registration in modules
- enable/disable hides Tabs

**Comment by mickaelandrieu** [comment]
Hello,

any ETA for this article ?

If it can make the process of accessing the new controllers easier, this is something we need to promote in official trainings.

Cheers

**Comment by jolelievre** [comment]
Hi @mickaelandrieu 

The doc is now available https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/tabs/#automatic-tab-registration
