### ISSUE TITLE
Document how multishop works

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/docs#466]
Document how multishop works in PrestaShop and how to make a module work with it.

**Comment by matks** [comment]
If I may enhance, it would be awesome to document
- the concept
- the database structure (and different types of entities)
- how it's being handled at ObjectModel level
- the things to keep in mind when dealing with multistore (especially the BO pages that allow to "change the context" at the top)
- as mentioned, how to make a module that modifies/interacts with a multishop entity/system from PrestaShop (example: a module that adds a multishop-aware form input inside a BO page)
- as mentioned, how to make a module that adds some multishop behavior
