### ISSUE TITLE
Using category variable in files tpl in Prestashop 1.7

### ISSUE THREAD

**Issue by annalisa2890** [PrestaShop/docs#49]
Hi,
I need the category name appears in product page. I try to find the variable in the code of ps_categorytree.tpl and I guess that's it: {$node.name}. I paste this variable in product.tpl but it doesn't work. Can you help me? Thanks a lot

**Comment by mickaelandrieu** [comment]
Hi @annalisa2890, I'm sorry this is not the right place to ask for help with your shop but about the documentation.

You can try to find some help in the official forum of [PrestaShop](https://www.prestashop.com/forums/) or on [Stackoverflow](https://stackoverflow.com/questions/tagged/prestashop) or even in our [Gitter](https://gitter.im/PrestaShop/General).
 
Regards,
