### ISSUE TITLE
Copy into the devdocs the "PS17 minor release lifecycle", but where ?

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#493]
@ttoine @eternoendless I'd like to copy into the devdocs the ["PS17 minor release lifecycle"](https://build.prestashop.com/news/ps17-minor-release-lifecycle/). Because in a few weeks it will be hidden into pages 2 or 3 of the Build.

I already did it for some articles; for exemple ["Introducing A New Bug Severity Classification"](https://build.prestashop.com/news/severity-classification/) was copied into https://devdocs.prestashop.com/1.7/contribute/contribution-process/how-issues-are-sorted/

According to you, where should I put it ? I'm not sure it should go, like other articles, into the "Contribution" section of the doc ...

Shall I create a new section "Release" ? Or I should put it into "Core Development" ?

**Comment by ttoine** [comment]
I really like the idea of a "Release" section, that would show the work done by the team to make a release happen.

**Comment by matks** [comment]
See https://github.com/PrestaShop/docs/pull/524

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/docs/pull/524
