### ISSUE TITLE
Write documentation about filtering grids

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/docs#497]
https://devdocs.prestashop.com/1.7/development/components/grid/tutorials/work-with-search-form/

This page was left blank and should be documented. It should be added in https://devdocs.prestashop.com/1.7/development/components/grid/#search-criteria Which talks about Filters component but no real link associated

This feature has evolved along the versions so it's important to detail the solutions for the different versions

Content to add in the doc:
- Definition::getFilters (which is the core o the feature, including for build the form in the grid)
- Filters class (since 1.7.5)
- SearchParametersResolver (automatic resolving in 175, explain limitations - double grid)
- FiltersBuilderResolver (automatic resolving since 176)
- Different filtering possibilities
  - controller/action for version previous to 176
  - filterId / GRID_ID + ResponseBuilder (since 1.7.6)
  - interface IdentifiableGridDefinitionFactoryInterface and use of CommonController (since 1.7.7)
- Thorough explanation of `SearchAndResetType` along with the different clean methods/routes

**Comment by mickaelandrieu** [comment]
Hello @jolelievre,

don't hesitate to ping me for a review once you've contributed this article.

Cheers

**Comment by jolelievre** [comment]
Hi @mickaelandrieu

Sure, here's the related PR https://github.com/PrestaShop/docs/pull/502

Thanks for the review ;)
