### ISSUE TITLE
Ease the setup of node and npm for development

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#533]
It seems the setup for Javascript development on PrestaShop is not the easiest, we should see how to improve it.
=> can be better docs and suggestions of useful tooling (nvm, https://github.com/nodenv/nodenv)
=> can be some easiest configuration or useful debug messages on startup

**Comment by NeOMakinG** [comment]
Gonna improve the doc when I'll have some times

**Comment by NeOMakinG** [comment]
https://github.com/PrestaShop/docs/pull/538

Feel free to give me some feedbacks/things to add to the documentation

**Comment by NeOMakinG** [comment]
Should be fine now, feel free to open it again if you don't think
