### ISSUE TITLE
Documentation for phpunit testing

### ISSUE THREAD

**Issue by howardnoz** [PrestaShop/docs#55]
Currently, documentation at http://doc.prestashop.com/display/PS17/PrestaShop+1.7+documentation mentions that tests can be used using selenium. Can there be documentation on how to run a phpunit test just to check if the data in a database is what I would expect it to be at time of running the phpunit test.

It'd be great if there were specifics on where to save our test, how to pull in necessary classes correctly, directory structure, etc.

My final goal is to run a phpunit test that indicates whether or not my module can insert orders into the database correctly.

**Comment by marcuslind90** [comment]
I would love this too. Any modern framework should allow unit testing, and there is no docs or resources covering this.

**Comment by mickaelandrieu** [comment]
Hi,

above all we are contributing a new section to help you launch the PrestaShop test suite, see the advancement here => https://github.com/PrestaShop/docs/pull/112/files#diff-ef23890eaebb9727294cf65bc19d7fa9

Regarding what you're looking for (learn PHPUnit, Selenium), my feeling is that the best place to do it is to read the documentation of these tools (https://phpunit.de/, http://webdriver.io/) and read in our testsuite how we use these tools.

Regards,
