### ISSUE TITLE
The new customization system problem

### ISSUE THREAD

**Issue by littfed** [PrestaShop/docs#56]
According guide:
[https://www.prestashop.com/forums/topic/549666-guide-the-new-customization-system-in-prestashop-17/](https://www.prestashop.com/forums/topic/549666-guide-the-new-customization-system-in-prestashop-17/)

There is problem in new customization system.
If my module creates a custom customization field for product and there is no any other customizations, `product`.`customizable` will set to '0' after product update (save).

Code is here:

**PrestaShop/src/Adapter/Product/AdminProductWrapper.php**
```
    function processProductCustomization() {
       ........
```

And that's why even if I set the value of the input `#product_customization_id` to include the customization in the cart - It not work, because:

**PrestaShop/classes/Cart.php**
```
    public function updateQty()
    ...
        if ($product->customizable) {
            return $this->_updateCustomizationQuantity((int)$quantity, (int)$id_customization, (int)$id_product, (int)$id_product_attribute, (int)$id_address_delivery, $operator);
        } else {
            return true;
        }

    ...

```

**Comment by mickaelandrieu** [comment]
Hi @littfed,

the tutorial you link is not from the PrestaShop Core team, so I can say if it's the expected behavior or not.

I think this more an issue to be addressed in the [Core](https://github.com/PrestaShop/PrestaShop/issues) than in the docs, isn't it?

Thanks for your report
