### ISSUE TITLE
List and explain all configuration variables

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/docs#562]
List and explain all configuration variables, if it is a multi-language field and allowed values:

- PS_OS_PAYMENT
- PS_OS_ERROR
- PS_LANG_DEFAULT
- ....

And include Prestashop version.

- EXAMPLE [1.4 - 1.6.1.24] (int number) : Example description
- EXAMPLE2 [from 1.7.5.0] (multi-lang text) : Example description

**Comment by matks** [comment]
Duplicated with https://github.com/PrestaShop/docs/issues/378
