### ISSUE TITLE
Explain each Webservice Ressource content

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/docs#590]
![image](https://user-images.githubusercontent.com/1533248/85143052-8875ce00-b249-11ea-8416-f70d1fb31f97.png)

**Comment by matks** [comment]
@Progi1984 Do you plan to describe all the properties of each API endpoint ?
Maybe we could simply copy-paste the whole WSDL ?

**Comment by Progi1984** [comment]
No the main content. 

@prismicio developpers contact me for having this information.

**Comment by eternoendless** [comment]
This is a start: https://devdocs.prestashop.com/1.7/webservice/reference/#available-resources

**Comment by Progi1984** [comment]
Thanks, it's perfect.
