### ISSUE TITLE
Have a list of "how to customize" for CRUD forms in Symfony

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#603]
Similar to the excellent work that was done for the grid, but for the form
https://devdocs.prestashop.com/1.7/development/components/grid/tutorials/

**Comment by kpodemski** [comment]
@thomasnares 

[there are examples](https://devdocs.prestashop-project.org/8/modules/sample-modules/extending-sf-form-with-upload-image-field/), but we lack internal linking between this and the Form component, we also lack explanation that this section is about Symfony code

https://devdocs.prestashop-project.org/8/development/components/form/

we also need to update this page:
https://devdocs.prestashop-project.org/8/development/components/form/form-theme/form-pages/
