### ISSUE TITLE
API Login not possible - undocumented Login-method

### ISSUE THREAD

**Issue by UdoLauer** [PrestaShop/docs#640]
Hello, 

please see https://www.prestashop.com/forums/topic/1027824-api-login-not-possible/?tab=comments#comment-3250773 for detailed information. 

I'm not sure if this is only a document-issue. But i got no help from the forum, Prestashop-Security, and Slack.

Best Regards

**Comment by matks** [comment]
@UdoLauer API endpoint : `/api` is accessible only if you have generated the appropriate .htaccess and enabled mod_rewrite in your Apache vhost

**Comment by cernekj** [comment]
HTTP Basic auth method doesn't work on client's server and using `ws_key` argument helps `http://prestashop.example.net/api/?ws_key=AUTH_KEY`. So it should be documented. (credits: <https://www.prestashop.com/forums/topic/1027824-api-login-not-possible/#comment-3250838> and <https://www.prestashop.com/forums/topic/430312-presta-api-keep-asking-for-username-password-authentication-required/#comment-2512161>).
Documentation for Apache mod_rewrite solution could be useful too as recommended here: <https://stackoverflow.com/questions/59937378/prestashop-webservice-api-login#61968411>.
