### ISSUE TITLE
XSRF issue on https://doc.prestashop.com/display/PS17/Managing+Multiple+Shops

### ISSUE THREAD

**Issue by justeen35** [PrestaShop/docs#652]
Hi, you have a XSRF issue on https://doc.prestashop.com/display/PS17/Managing+Multiple+Shops on page https://doc.prestashop.com/rest/webResources/1.0/resources . Modern browsers will flag this as a major security issue.

It's most likely a certificate issue

**Comment by matks** [comment]
Hi @justeen35 thanks for the report ! I confirm that page https://doc.prestashop.com/display/PS17/Managing+Multiple+Shops attempts to POST to endpoint https://doc.prestashop.com/rest/webResources/1.0/resources and it fails
![Capture d’écran 2020-08-04 à 10 29 30](https://user-images.githubusercontent.com/3830050/89271794-815e2000-d63d-11ea-82b8-5873ebb1728b.png)

**Comment by PierreRambaud** [comment]
ping @djodjo3 seems to concern your scope :sweat_smile: 
I'm closing it since it does not concern the devdoc website.
