### ISSUE TITLE
Documentation for compiling assets is incomplete

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/docs#663]
The page https://devdocs.prestashop.com/1.7/development/compile-assets/ does not state prerequisites for compiling the assets.

Using the latest stable release `1.7.6.7` on Windows 10.

To be able to run `npm install` in `themes/classic/_dev/`, there are the following prerequisites:
- use `node 10.22.0`. The version of `node-sass` used is not compatible with node 12.x (see https://github.com/sass/node-sass/issues/2794).
- install `windows-build-tools` using `npm i --global windows-build-tools`. This is required for `node-gyp`to work (see https://github.com/nodejs/node-gyp#on-windows)

I am still not able to get to work `npm run build` in the admin themes directories. There are several errors.

See also https://stackoverflow.com/questions/63454346

**Comment by NeOMakinG** [comment]
Hello @lmeyer1 ,

![image](https://user-images.githubusercontent.com/14963751/90609702-b86b2e80-e204-11ea-8647-ea0adf07d477.png)

There is a typo that I'll fix there, and will try to improve the doc, but atleast it's specified that 1.7.8 does support node 12.

By the way, we can't provide a complete documentation for every tools needed to run a build, as we doesn't maintain these, you can still refer to their proper documentations !

**Comment by matks** [comment]
@NeOMakinG did you fix the typo ? :) if yes we can close this issue

**Comment by kpodemski** [comment]
cc @NeOMakinG

**Comment by lmeyer1** [comment]
This issue is resolved for me. Documentation has been improved.
