### ISSUE TITLE
Is it invalid version 1.7.8 in docs?

### ISSUE THREAD

**Issue by likemusic** [PrestaShop/docs#683]
[The New Product Form](https://devdocs.prestashop.com/1.7/development/page-reference/back-office/product/form/) page point to version 1.7.8, that seems still not exists in [github-branches](https://github.com/PrestaShop/PrestaShop/branches/all).

Is it misprint in version or this is valid and created by coming soon, not implemented changes from some roadmap?

**Comment by matks** [comment]
This is valid. Future version 1.7.8 is being built on branch `develop`. When we reach Feature Freeze we'll create the `1.7.8.x` branch.

Everything is explained here 😉 https://devdocs.prestashop.com/1.7/project/release/patch-release-lifecycle/

**Comment by likemusic** [comment]
@matks thank you for your clarification. I haven't read this section yet :)

**Comment by matks** [comment]
> @matks thank you for your clarification. I haven't read this section yet :)

You're welcome. Nice github username by the way 😄 🎵 🎶
