### ISSUE TITLE
Link to a Google Doc inside 1-click upgrade documentation

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#773]
In page https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/#1-click-upgrade-module there is a link to a GoogleDoc in "Note about version +4.0.0"

This Google Doc might disappear one day if its owner leaves PrestaShop company. We should probably put this content in a better location.

@Quetzacoalt91 Would it be OK if I create a devdocs page with the Google Doc content ?

**Comment by Quetzacoalt91** [comment]
Sure, go ahead. There's no more reason to keep it as a Google Drive

**Comment by matks** [comment]
Note to myself: need to link this to https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/

**Comment by matks** [comment]
Should be fixed by https://github.com/PrestaShop/docs/pull/815
