### ISSUE TITLE
Document inner workings of our Behat test suite

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#800]
Although we rely on a very standard technology (Behat) for our integration tests, we have built specific helpers / conventions / systems / utils to test PrestaShop that fit the project specific needs. We have SharedStorage, a dedicated structure for storing Feature and Context files, reset utilities, a specific usage of tags...

We should document them (how they work, why they were introduced, how to use them) to help newcomers extend the test suite.

**Comment by zuk3975** [comment]
I think I've covered most of it here
https://github.com/PrestaShop/docs/pull/990#issuecomment-842091449

**Comment by matks** [comment]
Yes indeed 😄
