### ISSUE TITLE
The "Add to cart" button does not work Prestashop 1.7.7.2

### ISSUE THREAD

**Issue by Kssindri** [PrestaShop/docs#871]
Describe the bug
On the product sheet when you click on the "Add to cart" button, nothing happens and the product is not added to the cart then does not update automatically. You must refresh the page to be able to see your order add to cart .

Predictable behavior
Normally with previous versions, when you click on the "Add to cart" button, a window appears which recapitulates and summarizes the order which can allow us to continue the purchase or the order. But this window does not appear when you click on the "Add to cart" button.

Steps to reproduce

1- Go to 'https://afriqpharmacopee.com/'
2- Click on 'one of the products'
3- Click on the 'Add to cart' button
4- See error

**Comment by matks** [comment]
Hi @Kssindri this is not the right place to report an issue, see https://github.com/PrestaShop/PrestaShop/issues/new/choose

That being said, there seems to be issue in your shop only. I just checked our demo shop running 1.7.7.2 (https://demo.prestashop.com/#/en/front) it works very well.

When I check your product page, I see errors in JS console saying your Google Analytics module is not correctly configured. This can prevent the window to work.
