### ISSUE TITLE
Describe module name requirements

### ISSUE THREAD

**Issue by rmilecki** [PrestaShop/docs#880]
I find current documentation somehow ambiguous about allowed module names.

1. [Module file structure](https://devdocs.prestashop.com/1.7/modules/creation/module-file-structure/) suggests that module can be called "module_name" which clearly includes underscore in its name
2. [Translation domain](https://devdocs.prestashop.com/1.7/modules/creation/module-translation/new-system/#translation-domain) describes naming convention for translations (`Modules.Nameofthemodule.Specificpart`) and says that for the middle part "Only word characters (A-z, 0-9) are supported."
3. [Naming conventions](https://devdocs.prestashop.com/1.7/development/naming-conventions/) doesn't seem to mention modules naming at all.

Personally I was planning to release few modules using my company name and dash as prefix (`mysoft_`). That was to match PrestaShop convention (`ps_`). I'm really confused whether underscore is allowed or not.

If someone explains how modules should ba named, I could try improving documentation (prepare a pull request).

**Comment by eternoendless** [comment]
Hi @rmilecki

Modules names can have underscores but they don't work well with domain names. The `ps_` prefix is the exception to this rule (it is removed from the domain name).

**Comment by rmilecki** [comment]
Updated documentation says:
> Module names should contain only lower case and numbers.

That makes is clear, thank you @eternoendless
