### ISSUE TITLE
More info about cookies

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/docs#897]
In the Docs don't are info for the cookies functions used in prestashop.
With the GPDR is more important know this functions not only for developers it's important for the merchants too

**Comment by PierreRambaud** [comment]
Hi, could you tell us more about what you expect about cookies?

**Comment by TecnoHands** [comment]
Hello Pierre, What data store in the cookies per example, and for what those are used in prestashop.
Obviously this cookies are in the category of necesary strict but we need to know more details about this
I don't find this info and to complish with the GPDR The merchant and developers need to know this information to create the documentation for cookie page. Automated tools how cookie bot don't have this information either

**Comment by kpodemski** [comment]
@thomasnares 

let's take it, docs for component Cookie, how to set, how to read, what contains, etc. we'll discuss the details
