### ISSUE TITLE
Orders Api

### ISSUE THREAD

**Issue by SANDEEP2404** [PrestaShop/docs#969]
while we are getting the order, we are not found any fields to get by status and date range

https://presta.readers.in/api/orders

**Comment by SANDEEP2404** [comment]
Can you please expedite an at the earliest?

**Comment by matks** [comment]
Hi,

If you need help, please do not open a GitHub issue as we use GitHub issues only to discuss about bugs and new features for the PrestaShop project.

You can follow https://devdocs.prestashop.com/1.7/faq/i-need-help/ to find help

You might be interested in [PrestaShop Company’s support plans](https://www.prestashop.com/support).

**Comment by SANDEEP2404** [comment]
Hi,

Thanks for the inputs.
I have gone through the FAQs section but I could not get the necessary information.

All I am looking for is the API information where I can fetch Orders by Date range as I have to fetch orders placed in store on a daily basis.

Please help to find respective information.

Regards,
Sandeep

**Comment by matks** [comment]
@SANDEEP2404  You must use `date=1` parameter

Example: to fetch orders from 2021-05-01 to 2021-05-03

/api/orders?filter[date_add]=[2021-05-01,2021-05-03]&date=1

If you do /api/orders?filter[date_add]=[2021-05-01,2021-05-03] it will not work

**Comment by matks** [comment]
Details on https://devdocs.prestashop.com/1.7/webservice/getting-started/#available-parameters
