### ISSUE TITLE
Update Release Freeze process, can we merge bugfixes that do not fix regressions into branch?

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#972]
Current process states:

> Once this phase is started, Core maintainers create a git branch from develop branch which will carry the work to be done until the release (for 1.7.7.0, the branch name was 1.7.7.x). From this moment on, only bug fixes can be merged into this branch. Incidentally, this is also the branch where all future patch versions for this minor version will be developed on (hence the .x at the end).

https://devdocs.prestashop.com/1.7/project/release/patch-release-lifecycle/

This does not state whether
- only bugfixes that fix regressions can be merged in frozen branch
or
- any bugfix can be merged in frozen branch

We need to update the process to make it unambiguous.

**Comment by matks** [comment]
ping @PrestaShop/product-team can you confirm what should be updated

**Comment by marionf** [comment]
I suggest "only regressions fixes can be merged into this branch"

**Comment by eternoendless** [comment]
"Only changes that fix regressions"

**Comment by matks** [comment]
Submitted PR https://github.com/PrestaShop/docs/pull/973
